### ISSUE TITLE
Visions booster lists land, but there is no land

### ISSUE THREAD

**Issue by Meerkov** [Thyss/pack1pick1#10]
https://scryfall.com/search?unique=cards&as=grid&order=rarity&q=!Quirion-Ranger+e%3Avis+or+!Talruum-Champion+e%3Avis+or+!Undo+e%3Avis+or+!Bull-Elephant+e%3Avis+or+!Tar-Pit-Warrior+e%3Avis+or+!Funeral-Charm+e%3Avis+or+!Vision-Charm+e%3Avis+or+!Phyrexian-Walker+e%3Avis+or+!Song-of-Blood+e%3Avis+or+!Infantry-Veteran+e%3Avis+or+!Honorable-Passage+e%3Avis+or+!Ovinomancer+e%3Avis+or+!Desolation+e%3Avis+or+!Mountain+e%3Avis

**Comment by Meerkov** [comment]
Also, you'll notice there is only 13 non-basic land cards. The pack should have 15 non-basic land cards total after fixing the bug.

**Comment by Thyss** [comment]
The listing of lands is a default behaviour i coded, all sets get a basic land added unless i make exceptions per set. There is no reliable source i can fetch for what is actually included in which quantities in paper boosters that can make it easy to get all sets correct without doing hardcoded hacks per set. So some of the older sets that don't include a basic land just gets "nothing" (land included in the query string but not displayed)
In your example there is also a rare missing which should be the first card so there should be 14 cards there but i can't seem to replicate it since when i test i get rares in the packs.
