### ISSUE TITLE
P1P1 bot shows cards that aren't in TBD

### ISSUE THREAD

**Issue by Meerkov** [Thyss/pack1pick1#5]
It includes cards from planeswalker decks, etc.

See, e.g.:
https://scryfall.com/search?unique=cards&as=grid&order=rarity&q=!Karametra%27s-Blessing+e%3Athb+or+!Bronze-Sword+e%3Athb+or+!Irreverent-Revelers+e%3Athb+or+!Stampede-Rider+e%3Athb+or+!Hyrax-Tower-Scout+e%3Athb+or+!Witness-of-Tomorrows+e%3Athb+or+!Portent-of-Betrayal+e%3Athb+or+!Nyxborn-Marauder+e%3Athb+or+!Rumbling-Sentry+e%3Athb+or+!Iroas%27s-Blessing+e%3Athb+or+!Swimmer-in-Nightmares+e%3Athb+or+!Setessan-Petitioner+e%3Athb+or+!Stinging-Lionfish+e%3Athb+or+!Temple-of-Plenty+e%3Athb+or+!Plains+e%3Athb

Swimmer in Nightmares is not available in draft packs.

**Comment by Thyss** [comment]
This is due to how scryfall tags cards, before their release date they are not properly tagged as being available in boosters. This is reflected in the "info/spoiler" text and warning the bot produces instead of the list of cards when queried for an unreleased set. When a set is released and scryfall has tagged the cards properly with the tag they use to indicate that cards can come in boosters, cards from the planeswalker decks and buy a box promos etc should not show up in generated packs.

**Comment by Meerkov** [comment]
Can you add this info to the "Known Issues" section in the read me?

**Comment by Meerkov** [comment]
Also: I think this doesn't seem right.

https://api.scryfall.com/cards/0162a0b8-a2d1-4664-a445-331aee6d5175?format=json&pretty=true
  "booster": true,

https://api.scryfall.com/cards/ebc6b5ee-e764-444e-8b27-26e00f4b2074?format=json&pretty=true
  "booster": false,

The json looks like it correctly labels the non-booster card.
