### ISSUE TITLE
Feature Request: Use a service to generate packs

### ISSUE THREAD

**Issue by Meerkov** [Thyss/pack1pick1#8]
For example, http://mtgen.net/ seems to make fairly realistic looking packs.

Right now, packs can have some noticeable issues (e.g. packs missing a color, or not accounting for special slots correctly).

**Comment by Thyss** [comment]
Not a bad idea, but from the looks of it that is also not a perfect representation. Although a lot closer to reality than my implementation since i don't usually take into account for special treatments almost at all.
But i can't use that tool since from what i can see its only an online tool and doesn't provide an api.
Also, from previous research i did when i wrote the generation of packs, wotc doesn't disclose their algorithm at all and i haven't found anyone rich enough to map enough boxes to produce an accurate representation of boosters so most of the tools that generate boosters are more or less accurate "educated guesses". My generation is not perfect since its closer to "true randomness" if you are familiar with that term. Technically you could get a pack of 1 rare, 3 uncommons of the same card and the rest commons of exactly the same card with "true randomness", i have taken measures to prevent this however and "remove" a card from the set of each iteration of picking cards when building the boosters.

**Comment by Meerkov** [comment]
To be honest, I wrote my own bot in about 30 minutes just now.
